### PR TITLE
WIP: redis-py 3.0.x support

### PR DESCRIPTION
**Pull request by Grokzen**
This branch is the current WIP to merge and update all code to make it compatible with redis-py >= 3.0.0,<3.1.0 releases. Current plan is to sort out all the broken stuff and make it work again with most basic commands before moving to support all new commands and features as that needs more exploration on how they work in a clustered environment.

Solves #295

### CODE REVIEW

**Comment by CheViana** [comment]
would love to have these changes, ready to help

**Comment by Grokzen** [comment]
@CheViana It is moving along good. The features that i have no clue about right now is the latest new features and commands that was added into redis 5.0.x series. Streams for example. I have no idea how they perform or work or behave in a clustered envrionment and if they are really ment to be supported by a cluster or not. I got most other things covered right now and it do not seems to be that difficult to deal with, only the backwards incompatible things is the real issue in a way.

**Comment by yakhira** [comment]
it seems to be stuck year ago

**Comment by Grokzen** [comment]
Most tests now work as expected or have had a skip block added to them either because of crossslot reasons or they should hardfail. Noteable change is that i ripped out the sort method and will make a fallback onto the old crossslot error provided by redis itself.

**Pull request merged**
