### PR TITLE
removed assert from evaluation of dict, func: utils.is_dict.

### PR DESCRIPTION
**Pull request by gmolight**
Removing assert from utils.is_dict. Removing the risk of executing the passed down variable when assert  evaluates the variable. In addition set a default None return, since Nothing is already expected upstream.

### CODE REVIEW

**Comment by Grokzen** [comment]
Tests failed and would it not be better if you changed it to `return isinstance(d, dict)` ?

**Comment by Grokzen** [comment]
Also, you would have to correct the unit tests so they would pass with this new logic becuas they are currently failing.

**Comment by gmolight** [comment]
ok I will do so

**Comment by gmolight** [comment]
sorry about that ..

**Comment by Grokzen** [comment]
@gmolight I will go through this and review it sometime during the week

**Comment by Grokzen** [comment]
@gmolight I implemented this fix in a different way then this but with the same result. The commit is 4738b6df9dd802a24ada8ff9920a3285306a33f3

I felt that raising a more proper exception on any error was better. Credit is till in your name even if i did the commit :]

Thanks for the idea and initial work.

**Pull request closed without merging**
