### PR TITLE
Enable SCRIPT commands LOAD/FLUSH/EXISTS/EVALSHA

### PR DESCRIPTION
**Pull request by alisaifee**
Testing done
 * As per tests in [test_scripting.py](https://github.com/alisaifee/redis-py-cluster/blob/script-loading/tests/test_scripting.py)
 * Calling a registered script against a slot on a new node which doesn't have the script loaded.
 * Calling a registered csript on a slot that was moved to a different node which doesn't have the script loaded.

Not implemented
 * `SCRIPT KILL`
 * loading a script in a pipeline.

### CODE REVIEW

**Comment by Grokzen** [comment]
@alisaifee You can add yourself to authors list/file. Also you need to add a line in the CHANGES file describing this change, add it in Next Release section. I guess also you need to start documenting the scripting solution with supported features, limitations and problems. One example of one thing that needs to be documented is the limitation that you must handle MOVED/ASK errors manually in the lua code and that it will not be provided within this library. I can continue to document things while testing scripting  if you start the work.

**Comment by Grokzen** [comment]
Also are you planning to add more features or do you consider this code to be done?

**Comment by alisaifee** [comment]
Regarding unimplemented features:
* I can't think of a safe implementation for `SCRIPT KILL` that is compliant with the implementation in `StrictRedis`. One possibility is to simply iterate over all masters and issue the command and return `True` if any node did have a script running, else raise the underlying exception from any of the nodes if none had any scripts running.
* Since there appears to be some work being done on pipelines in parallel, I feel it would be safer to hold off on that implementation for now.

I'll update authors/changes section and start work on the documentation for scripting support.

**Comment by Grokzen** [comment]
LGTM :] Thank you very much for this

**Pull request merged**
