### PR TITLE
Fix a bug that was returned the key nodes_callbacks that was removed

### PR DESCRIPTION
**Pull request by Ozahata**
- The changes was made in the commit 4a95342.
     First was removed in line 146 but had other change in 1024 that returned the key.

### CODE REVIEW

**Comment by Grokzen** [comment]
@Ozahata If this is the one you want me to merge, please close the other one and refer to this PR in that PR.

**Comment by Grokzen** [comment]
@Ozahata you need to change the destination branch for this PR. The master branch is only used when i create a official release. All changes should me merged into the default branch named `unstable`. You can change the destination branch inside this PR without having to close this one and create a new one.

**Comment by Grokzen** [comment]
@Ozahata I also need a description on what the problem is that this change will solve? Is there something that breaks when you run the code? Is this just a code cleanup or what will it affect if i merge this change? I do not get why we need this.

**Comment by Ozahata** [comment]
@Grokzen I cannot change the destination branch in this PR (The edit button only allow me to edit the title) and all the answers that I see tell to close the PR and create a new one.
Since the PR #143 is the same, I will re-open and write the description there.

**Pull request closed without merging**
