### PR TITLE
Fix a bug that was returned the key nodes_callbacks that was removed

### PR DESCRIPTION
**Pull request by Ozahata**
- The changes was made in the commit 4a953420e004385f6783b34ed43755e1e0c5ebd3.
     First was removed in line 146 but had other change in 1024 that returned the key.

### CODE REVIEW

**Comment by Ozahata** [comment]
Wrong PR requested, please check [143](https://github.com/Grokzen/redis-py-cluster/pull/143)

**Comment by Ozahata** [comment]
The problem occurs when I was changing my redis to redis cluster with pipeline.
In this part of the code I don't care about the transaction, when I tried the example below I received an exception.
```python2
with rds.pipeline(transaction=False) as pipe:
    pipe.incr('test:counter')
    ...
```
Exception:
```
...
  File "/home/user/.virtualenvs/sandbox/lib/python2.7/site-packages/rediscluster/client.py", line 1023, in pipeline
    nodes_callbacks=self.nodes_callbacks,
AttributeError: 'RedisCluster' object has no attribute 'nodes_callbacks'
```
Checking for the problem, I saw that has not reference about it anymore and in the blame I saw the commit 4a95342

**Comment by Grokzen** [comment]
@Ozahata Sounds good, i will take a look at the fix and see if i can replicate your issue before i merge this.

**Comment by Grokzen** [comment]
@Ozahata To fix the broken tests, you just need to pull down my latest changes in unstable branch where i fixed the issue and then rebase you branch ontop of those changes and push your branch again.

**Comment by Grokzen** [comment]
@Ozahata No you should not merge the remote tracking branch unstable into your branch. You have to revert out from the commit and `Rebase` your commit on top of my latest commit in my `unstable` branch.

**Comment by Ozahata** [comment]
@Grokzen Sorry for my misunderstood

**Comment by Grokzen** [comment]
@Ozahata Hi. I manually merged this into usntable and i also added a regression test for the code you provided above. I also added a line in the change-log file mentioning the fix. I added your name to that fix because you commited the fix. If you want to change the name on that line to something else, feel free to open up a new PR with whatever name you desire.

**Pull request merged**
