### PR TITLE
Use Binary and Unicode literals instead of the helpers from redis-py

### PR DESCRIPTION
**Pull request by imnotjames**
These helpers are being removed in the next version of `redis-py` (`>=3.0`).  With that in mind, I cleaned up and converted everything to the same systems that are used by the new version of `redis-py`.

This should help us upgrade to `redis-py >= 3.0`

### CODE REVIEW

**Comment by imnotjames** [comment]
That's weird - it failed the checks because of some AWS issues?

**Comment by Grokzen** [comment]
What AWS issue? This repo do not use any AWS features? Unless you mean on the travis side itself or that coveralls is broken?

**Comment by imnotjames** [comment]
Yeah, it was on the travis side of things - it couldn't retrieve the blob for travis to run Python 3.4 - but it seems to be cleared up now!

**Comment by imnotjames** [comment]
Rebased against unstable - not sure what went wonky there.

**Pull request closed without merging**
